### ISSUE TITLE
Problem with PWSCF run in Aluminum tutorial

### ISSUE THREAD

**Issue by fabioaffinito** [yambo-code/tutorials#2]
Hi folks! 
I've encountered this problem when running pw.x (v7.2) on the Aluminum test case (https://github.com/yambo-code/tutorials/blob/master/Aluminum/PWSCF/gs.in)

  ```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine electrons (1):
     charge is wrong
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
The only way I found to complete the calculation was to increase (a lot!) the smearing. Can you give a look at it?

Ciao,

F.

**Comment by sangallidavide** [comment]
Fixed with commit https://github.com/yambo-code/tutorials/commit/4d695587350efc531c7facacac1dbfbbc30cca31
